// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8SXae-S5aVhS3MFwo_qbJJOQ5Rtb75Cs',
    appId: '1:31944510254:web:e6a82a69ac5c3d6b1308bf',
    messagingSenderId: '31944510254',
    projectId: 'himpunapp',
    authDomain: 'himpunapp.firebaseapp.com',
    storageBucket: 'himpunapp.firebasestorage.app',
    measurementId: 'G-1TZDHGCY7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxS2wIh4zKEnDqH6y0nyotmTf7o7dqI-4',
    appId: '1:31944510254:android:98fa305358ebf10b1308bf',
    messagingSenderId: '31944510254',
    projectId: 'himpunapp',
    storageBucket: 'himpunapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwZmn3R3nCEfzWr5MNWUR0Oq6qZHYza3g',
    appId: '1:31944510254:ios:810eb56bb8b223281308bf',
    messagingSenderId: '31944510254',
    projectId: 'himpunapp',
    storageBucket: 'himpunapp.firebasestorage.app',
    iosBundleId: 'com.example.himpunapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwZmn3R3nCEfzWr5MNWUR0Oq6qZHYza3g',
    appId: '1:31944510254:ios:810eb56bb8b223281308bf',
    messagingSenderId: '31944510254',
    projectId: 'himpunapp',
    storageBucket: 'himpunapp.firebasestorage.app',
    iosBundleId: 'com.example.himpunapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8SXae-S5aVhS3MFwo_qbJJOQ5Rtb75Cs',
    appId: '1:31944510254:web:7d55daa7f618ffc71308bf',
    messagingSenderId: '31944510254',
    projectId: 'himpunapp',
    authDomain: 'himpunapp.firebaseapp.com',
    storageBucket: 'himpunapp.firebasestorage.app',
    measurementId: 'G-930RWYH9GL',
  );
}
