// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRuB1oqhNeo5XU8OXaThmANCHQzWLk46s',
    appId: '1:300814379649:web:f13832fec2db2d6672fb80',
    messagingSenderId: '300814379649',
    projectId: 'fir-crud-kamil',
    authDomain: 'fir-crud-kamil.firebaseapp.com',
    storageBucket: 'fir-crud-kamil.firebasestorage.app',
    measurementId: 'G-BT97WTLP4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1wPxCBnC15EZRmO-J8UbrVs8sRmODAYA',
    appId: '1:300814379649:android:847f27eb309ef88c72fb80',
    messagingSenderId: '300814379649',
    projectId: 'fir-crud-kamil',
    storageBucket: 'fir-crud-kamil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtBEMZMR7L9RCUgZXRtC39AtR9cTt_nWI',
    appId: '1:300814379649:ios:d2d824f2b238cb8e72fb80',
    messagingSenderId: '300814379649',
    projectId: 'fir-crud-kamil',
    storageBucket: 'fir-crud-kamil.firebasestorage.app',
    iosBundleId: 'com.example.crudlocaldb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtBEMZMR7L9RCUgZXRtC39AtR9cTt_nWI',
    appId: '1:300814379649:ios:d2d824f2b238cb8e72fb80',
    messagingSenderId: '300814379649',
    projectId: 'fir-crud-kamil',
    storageBucket: 'fir-crud-kamil.firebasestorage.app',
    iosBundleId: 'com.example.crudlocaldb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRuB1oqhNeo5XU8OXaThmANCHQzWLk46s',
    appId: '1:300814379649:web:18e0d91048e0a24972fb80',
    messagingSenderId: '300814379649',
    projectId: 'fir-crud-kamil',
    authDomain: 'fir-crud-kamil.firebaseapp.com',
    storageBucket: 'fir-crud-kamil.firebasestorage.app',
    measurementId: 'G-RRGHZW1EK3',
  );
}
